base_url: /
title: Ronald van Zuijlen
author: Ronald van Zuijlen
description: "Personal blog of Ronald van Zuijlen."
keywords: "developer, utrecht"
markdown: kramdown 
highlighter: rouge 

exclude: ['README.md']
